# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./server/src/:/server/src/
    

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: ranking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes: 
  pgdata: