# docker-compose.yml
version: "3"
services:

  reactapp:
    build:
      dockerfile: DockerfileApp
      context: .
    depends_on:
      - server
    ports:
      - "3000:3000"  
    volumes:
    - ./react-app/src/:/react-app/src/

  server:
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./server/src/:/server/src/
    
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: ranking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes: 
  pgdata: